import { RuleEvaluationData } from './types';

export const sampleRuleEvaluationData: RuleEvaluationData = {
  caseId: 'CASE-2024-001234',
  infectionType: 'CLABSI',
  summary: {
    totalRules: 12,
    passedRules: 8,
    failedRules: 2,
    notEvaluatedRules: 2,
    requiredRulesPassed: 6,
    requiredRulesTotal: 8,
    overallConfidence: 0.85,
    evaluationTimestamp: '2024-01-15T10:30:00Z',
  },
  evaluations: [
    {
      ruleId: 'CLABSI-001',
      ruleName: 'Central Line Present',
      category: 'device',
      status: 'pass',
      isRequired: true,
      description: 'Patient must have a central line in place',
      rationale: 'Central line documented in medical records for the required period',
      confidence: 0.95,
      evidence: [
        {
          id: 'ev-001',
          type: 'procedure_note',
          content: 'Central venous catheter inserted in right internal jugular vein',
          timestamp: '2024-01-10T08:00:00Z',
          strength: 'strong',
        },
        {
          id: 'ev-002',
          type: 'nursing_note',
          content: 'CVC site assessed, dressing clean and dry',
          timestamp: '2024-01-14T12:00:00Z',
          strength: 'strong',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-002',
      ruleName: 'Positive Blood Culture',
      category: 'lab',
      status: 'pass',
      isRequired: true,
      description: 'At least one positive blood culture with recognized pathogen',
      rationale: 'Blood culture positive for Staphylococcus aureus',
      confidence: 0.98,
      evidence: [
        {
          id: 'ev-003',
          type: 'lab_result',
          content: 'Blood culture: Staphylococcus aureus (MSSA) identified',
          timestamp: '2024-01-12T14:30:00Z',
          strength: 'strong',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-003',
      ruleName: 'Timeline Criteria',
      category: 'temporal',
      status: 'pass',
      isRequired: true,
      description: 'Positive culture collected >2 calendar days after line insertion',
      rationale: 'Blood culture collected 2 days after central line placement',
      confidence: 0.92,
      evidence: [
        {
          id: 'ev-004',
          type: 'timeline_analysis',
          content: 'Line insertion: 2024-01-10, Culture collection: 2024-01-12 (2 days)',
          strength: 'strong',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-004',
      ruleName: 'Clinical Signs',
      category: 'clinical',
      status: 'pass',
      isRequired: true,
      description: 'Patient exhibits fever (>38°C) or other signs of infection',
      rationale: 'Patient had documented fever and elevated WBC count',
      confidence: 0.88,
      evidence: [
        {
          id: 'ev-005',
          type: 'vital_signs',
          content: 'Temperature: 38.9°C',
          timestamp: '2024-01-12T06:00:00Z',
          strength: 'strong',
        },
        {
          id: 'ev-006',
          type: 'lab_result',
          content: 'WBC: 15,200/μL (elevated)',
          timestamp: '2024-01-12T07:00:00Z',
          strength: 'moderate',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-005',
      ruleName: 'No Alternate Source',
      category: 'exclusion',
      status: 'fail',
      isRequired: true,
      description: 'No other apparent source of bloodstream infection',
      rationale: 'Patient has concurrent urinary tract infection',
      confidence: 0.75,
      evidence: [
        {
          id: 'ev-007',
          type: 'urine_culture',
          content: 'Urine culture positive for E. coli >100,000 CFU/mL',
          timestamp: '2024-01-12T08:00:00Z',
          strength: 'moderate',
        },
        {
          id: 'ev-008',
          type: 'clinical_note',
          content: 'Patient reports dysuria and frequency',
          timestamp: '2024-01-11T14:00:00Z',
          strength: 'weak',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-006',
      ruleName: 'Not Present on Admission',
      category: 'temporal',
      status: 'pass',
      isRequired: true,
      description: 'Infection was not present or incubating at admission',
      rationale: 'Patient admitted without signs of infection; symptoms developed 48h after admission',
      confidence: 0.90,
      evidence: [
        {
          id: 'ev-009',
          type: 'admission_note',
          content: 'No fever, WBC normal on admission',
          timestamp: '2024-01-10T10:00:00Z',
          strength: 'strong',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-007',
      ruleName: 'Antibiotic Treatment',
      category: 'clinical',
      status: 'pass',
      isRequired: false,
      description: 'Patient received appropriate antibiotic therapy',
      rationale: 'Antibiotics initiated based on culture results',
      confidence: 0.93,
      evidence: [
        {
          id: 'ev-010',
          type: 'medication_order',
          content: 'Vancomycin 1g IV q12h started',
          timestamp: '2024-01-12T15:00:00Z',
          strength: 'strong',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-008',
      ruleName: 'Same Organism Match',
      category: 'lab',
      status: 'not_evaluated',
      isRequired: false,
      description: 'Organism from blood culture matches organism from catheter tip',
      rationale: 'Catheter tip culture not performed',
      confidence: 0.0,
      evidence: [],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-009',
      ruleName: 'Secondary BSI Exclusion',
      category: 'exclusion',
      status: 'fail',
      isRequired: true,
      description: 'BSI is not secondary to infection at another site',
      rationale: 'May be secondary to urinary tract infection',
      confidence: 0.68,
      evidence: [
        {
          id: 'ev-011',
          type: 'assessment',
          content: 'Concurrent UTI with same organism cannot be ruled out as primary source',
          strength: 'moderate',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-010',
      ruleName: 'Immunocompromised Status',
      category: 'clinical',
      status: 'not_evaluated',
      isRequired: false,
      description: 'Patient immunocompromised status assessment',
      rationale: 'Insufficient data to determine immunocompromised status',
      confidence: 0.0,
      evidence: [],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-011',
      ruleName: 'Line Removal',
      category: 'device',
      status: 'pass',
      isRequired: false,
      description: 'Central line removed or replaced',
      rationale: 'Central line removed after positive culture',
      confidence: 0.96,
      evidence: [
        {
          id: 'ev-012',
          type: 'procedure_note',
          content: 'Central venous catheter removed from right IJ',
          timestamp: '2024-01-13T09:00:00Z',
          strength: 'strong',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
    {
      ruleId: 'CLABSI-012',
      ruleName: 'Patient Age Criteria',
      category: 'clinical',
      status: 'pass',
      isRequired: true,
      description: 'Patient meets age criteria for surveillance',
      rationale: 'Patient is 58 years old, meets adult criteria',
      confidence: 1.0,
      evidence: [
        {
          id: 'ev-013',
          type: 'demographics',
          content: 'Date of birth: 1965-07-15 (Age: 58)',
          strength: 'strong',
        },
      ],
      evaluatedAt: '2024-01-15T10:30:00Z',
    },
  ],
};
